class Sizes(object):
    CELL_WIDTH  = 90
    CELL_HEIGHT = 90

    QUADRANT_WIDTH  = 270
    QUADRANT_HEIGHT = 270

    FIXED_FIGURE_SIZE = 10
    FIGURE_SIZE_PARAM = 20

    BOX_WIDTH  = 540
    BOX_HEIGHT = 540
