class Sizes(object):
    CELL_WIDTH  = 80
    CELL_HEIGHT = 80

    QUADRANT_WIDTH  = 240
    QUADRANT_HEIGHT = 240

    FIXED_FIGURE_SIZE = 10
    FIGURE_SIZE_PARAM = 20

    BOX_WIDTH  = 480
    BOX_HEIGHT = 480
